version: '3.8'
services:
  ewm-service:
    build: Main
    image: "main"
    container_name: dock_main
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
  stats-server:
    build: Statistics
    image: "statistics"
    container_name: dock_stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stats
  stats-db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
